### ISSUE TITLE
Needs an update to support Broccoli >= 1.0

### ISSUE THREAD

**Issue by adambullmer** [johno/broccoli-csslint#5]
```Warning: CSSLinter: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md```

Looks like this project needs a quick update to be based off the `broccoli-plugin` base class.

**Comment by SergeAstapov** [comment]
This is fixed in #6.

@johno Could you please release new version of broccoli-csslint to npm?

**Comment by johno** [comment]
Sure, looks like it should be a major version?

**Comment by johno** [comment]
Published as `broccoli-csslint@2.0.0`

**Comment by johno** [comment]
Thanks for fixing @SergeAstapov!
